version: "3.7"

services:
  brownbag:
    image: brownbag:${VERSION}
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
    - ${PORT_NUMBER}:${PORT_NUMBER}
    networks:
      app_nw:
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1

networks:
  app_nw:
    driver: overlay